# Generated by Django 4.2.21 on 2025-05-10 16:01

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250510_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divulgações',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(default=datetime.date.today, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 720, 'width': 1280}}, verbose_name='Imagem')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Divulgação',
                'verbose_name_plural': 'Divulgações',
            },
        ),
    ]
