# Generated by Django 4.2.21 on 2025-05-10 17:09

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_garcom_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Restaurante')),
                ('logo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria🍽️', 'verbose_name_plural': '1. Categorias🍽️'},
        ),
        migrations.AlterModelOptions(
            name='divulgacoes',
            options={'verbose_name': 'Divulgação📢', 'verbose_name_plural': '3. Divulgações📢'},
        ),
        migrations.AlterModelOptions(
            name='garcom',
            options={'verbose_name': 'Garçom👨', 'verbose_name_plural': '4. Garçons👨'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa🪑', 'verbose_name_plural': '5. Mesas🪑'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto🍽️', 'verbose_name_plural': '2. Produtos🍽️'},
        ),
    ]
