# Generated by Django 4.2.21 on 2025-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_informacoes_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacoes',
            options={'verbose_name': 'Informação⚙️', 'verbose_name_plural': '6. Informações⚙️'},
        ),
        migrations.AddField(
            model_name='informacoes',
            name='sobre',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Sobre'),
        ),
    ]
