# Generated by Django 4.2.21 on 2025-05-22 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_informacoes_options_informacoes_sobre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': '1. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='divulgacoes',
            options={'verbose_name': 'Divulgação', 'verbose_name_plural': '3. Divulgações'},
        ),
        migrations.AlterModelOptions(
            name='garcom',
            options={'verbose_name': 'Garçom', 'verbose_name_plural': '4. Garçons'},
        ),
        migrations.AlterModelOptions(
            name='informacoes',
            options={'verbose_name': 'Informação️', 'verbose_name_plural': '6. Informações'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': '5. Mesas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': '2. Produtos🍽'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='divulgacoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='garcom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informacoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número do pedido')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mesa', verbose_name='Nº da Mesa')),
                ('preco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_preco', to='core.produto', verbose_name='Preço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_produto', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Gestor de Pedidos',
                'verbose_name_plural': '7. Gestor de Pedidos',
            },
        ),
    ]
