# Generated by Django 4.2.21 on 2025-05-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_categoria_options_alter_divulgacoes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='produto',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto', verbose_name='Produto')),
            ],
        ),
    ]
