# Generated by Django 4.2.21 on 2025-05-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pedidos_preco_remove_pedidos_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': '2. Produtos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
