# Generated by Django 4.2.21 on 2025-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={},
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparo', 'Em preparo'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
