# Generated by Django 4.2.21 on 2025-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedidos_hora_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
