# Generated by Django 4.2.21 on 2025-06-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pedidos_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divulgacoes',
            name='produto',
        ),
        migrations.AddField(
            model_name='divulgacoes',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto'),
        ),
    ]
