# Generated by Django 4.2.21 on 2025-06-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divulgacoes',
            name='titulo',
        ),
        migrations.AddField(
            model_name='divulgacoes',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100, verbose_name='Nome da Divulgação'),
            preserve_default=False,
        ),
    ]
