# Generated by Django 4.2.21 on 2025-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_divulgacoes_titulo_divulgacoes_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoes',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], default='claro', max_length=20, verbose_name='Tema do Cardápio'),
        ),
    ]
